apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-rhtap-mc-unsuported-runtime-5lde
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ouhv-tenant/mc-unsupported-runtime/devfile-sample-python-basic-rhtap-mc-unsuported-runtime-5lde@sha256:31e6cfb0a423071186d361c02ae1adb009d4ac09b008835367d6d6f6a8de9bd4
        name: my-python
        resources: {}
status: {}
